# Generated by Django 5.0.4 on 2024-06-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Modern_Spanish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('apellido_paterno', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('apellido_materno', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('correo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('telefono', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=1)),
                ('prevision', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
            ],
            options={
                'db_table': 'myapp_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'myapp_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('apellido_paterno', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('apellido_materno', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('correo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('telefono', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=1)),
            ],
            options={
                'db_table': 'myapp_especialista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappHistorialatencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'myapp_historialatencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappHorariosatencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_cita', models.IntegerField()),
            ],
            options={
                'db_table': 'myapp_horariosatencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.IntegerField()),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'myapp_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyappReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_reserva', models.IntegerField()),
                ('agendar_hora', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'myapp_reserva',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historialatencion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='historialatencion',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='horariosatencion',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='historialatencion',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario_atencion',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Especialista',
        ),
        migrations.DeleteModel(
            name='HistorialAtencion',
        ),
        migrations.DeleteModel(
            name='HorariosAtencion',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
