# Generated by Django 5.0.4 on 2024-06-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reserva_comentario_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosatencion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
