# Generated by Django 5.0.4 on 2024-06-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notificacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariosatencion',
            unique_together={('fecha', 'hora_inicio', 'especialista')},
        ),
    ]
