# Generated by Django 5.0.4 on 2024-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('solucionado', 'Solucionado'), ('cerrado', 'Cerrado'), ('confirmado', 'Confirmado')], default='asignado', max_length=20),
        ),
    ]
