# Generated by Django 5.0.6 on 2024-07-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha',
        ),
    ]
